env:
  global:
    - secure: TeiN4v6xNRQYOX8ahW9XYftnxfLVUw3e3M9PmfxHk6UPLZmPXAeOYXjT9yDP86cnErwslxPbE33d/O8zzOexbfDY/kEgo5nfP979Zx58BS2GgeudPsVVpWn7X2KbnvocC2cHIkJJt4Xoe+BgMisQvN1Cgc7AblnDdA84JPAyE3M=
notifications:
  email:
    - philippe.delrieu@free.fr
before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
install:
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - sudo apt-get install cargo
  - sudo apt-get install libportmidi-dev
env:
  - RUST_TEST_TASKS=1
script:
  - cargo build
os:
  - linux


